### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by Mm2PL** [macmv/among-us-server#1]
The commit history and code for this project certainly look interesting. I would like to know what are the goals of this project and who is it for. Is this a proxy or a full-on clean-room reverse engineering of the game's servers or even something completely different?

**Comment by macmv** [comment]
This started out being a full among us server, that would do everything the matchmaking server couldn't. Then I realized the local games tab existed, and realized it would be easier to make a grpc proxy between a host and everyone else. So I ended up with this design: A grpc server, on aws, listens for incoming host connections. A client, with their game open, runs this code, and passes it the `-host` flag. The aws server will hear this connection, and then start talking with the client that is hosting. The other clients then all run this binary, and pass it no flags. When they go to their "local games" list on the Among Us client, they will be able to see a game that is created by this program. When they join that game, it will route their traffic through the aws server, back to the hosting client, using grpc.

A couple optimizations will be made. The among us client uses a UDP connection, and it sends a "confirm" packet to the other party, whenever it gets a packet. This code would generate those packets automatically. That alone will reduce the amount of data going through grpc by half.

As for reverse engineering, I spent quite a while on that. I had gotten as far as I could with the server list packet, as I was trying to make a whole rewrite to the online games tab. However I am not very experienced with reverse engineering, and I didn't get too far. 

As I was working on this, the devs announced that they were going to make this game open source. That, along with the patches to their matchmaking system, made this sort of obsolete. This was mostly started because my friends and I couldn't join games with each other, as the matchmakers are full. Since that has been (sort of) patched, I don't see a need for this repository.

Feel free to take this code and run with it. I probably won't be working on it anymore. If it gets some interest I might come back to it. Also, if someone figures out a relatively complete packet spec, I will probably come back to it, and change the project from a proxy back to a full server implementation.
